use super::*;

include!("sprite_data_macro.rs");

// Note: images that have a "2" version go together (opposite gostek direction).

sprites! {
    // The order of the gostek images must match the order of the Team2 versions
    // listed below. Keep both lists together, the range Gostek::Stopa to
    // Gostek::Team2Lecistopa2 is checked for a size restriction.

    Gostek {
        Stopa              = "gostek-gfx/stopa.bmp"
        Stopa2             = "gostek-gfx/stopa2.bmp"
        Noga               = "gostek-gfx/noga.bmp"
        Noga2              = "gostek-gfx/noga2.bmp"
        Udo                = "gostek-gfx/udo.bmp"
        Udo2               = "gostek-gfx/udo2.bmp"
        Biodro             = "gostek-gfx/biodro.bmp"
        Biodro2            = "gostek-gfx/biodro2.bmp"
        Klata              = "gostek-gfx/klata.bmp"
        Klata2             = "gostek-gfx/klata2.bmp"
        Morda              = "gostek-gfx/morda.bmp"
        Morda2             = "gostek-gfx/morda2.bmp"
        Ramie              = "gostek-gfx/ramie.bmp"
        Ramie2             = "gostek-gfx/ramie2.bmp"
        Reka               = "gostek-gfx/reka.bmp"
        Reka2              = "gostek-gfx/reka2.bmp"
        Dlon               = "gostek-gfx/dlon.bmp"
        Dlon2              = "gostek-gfx/dlon2.bmp"
        Lancuch            = "gostek-gfx/lancuch.bmp"
        Helm               = "gostek-gfx/helm.bmp"
        Helm2              = "gostek-gfx/helm2.bmp"
        Badge              = "gostek-gfx/badge.bmp"
        Badge2             = "gostek-gfx/badge2.bmp"
        Cygaro             = "gostek-gfx/cygaro.bmp"
        Cygaro2            = "gostek-gfx/cygaro2.bmp"
        Metal              = "gostek-gfx/metal.bmp"
        Metal2             = "gostek-gfx/metal2.bmp"
        Zloto              = "gostek-gfx/zloto.bmp"
        Zloto2             = "gostek-gfx/zloto2.bmp"
        Zlotylancuch       = "gostek-gfx/zlotylancuch.bmp"
        Kap                = "gostek-gfx/kap.bmp"
        Kap2               = "gostek-gfx/kap2.bmp"
        Dred               = "gostek-gfx/dred.bmp"
        Hair1              = "gostek-gfx/hair1.bmp"
        Hair12             = "gostek-gfx/hair12.bmp"
        Hair2              = "gostek-gfx/hair2.bmp"
        Hair22             = "gostek-gfx/hair22.bmp"
        Hair3              = "gostek-gfx/hair3.bmp"
        Hair32             = "gostek-gfx/hair32.bmp"
        Hair4              = "gostek-gfx/hair4.bmp"
        Hair42             = "gostek-gfx/hair42.bmp"
        Kamizelka          = "gostek-gfx/kamizelka.bmp"
        Kamizelka2         = "gostek-gfx/kamizelka2.bmp"
        RannyKlata         = "gostek-gfx/ranny/klata.bmp"
        RannyKlata2        = "gostek-gfx/ranny/klata2.bmp"
        RannyMorda         = "gostek-gfx/ranny/morda.bmp"
        RannyMorda2        = "gostek-gfx/ranny/morda2.bmp"
        RannyNoga          = "gostek-gfx/ranny/noga.bmp"
        RannyNoga2         = "gostek-gfx/ranny/noga2.bmp"
        RannyRamie         = "gostek-gfx/ranny/ramie.bmp"
        RannyRamie2        = "gostek-gfx/ranny/ramie2.bmp"
        RannyReka          = "gostek-gfx/ranny/reka.bmp"
        RannyReka2         = "gostek-gfx/ranny/reka2.bmp"
        RannyUdo           = "gostek-gfx/ranny/udo.bmp"
        RannyUdo2          = "gostek-gfx/ranny/udo2.bmp"
        RannyBiodro        = "gostek-gfx/ranny/biodro.bmp"
        RannyBiodro2       = "gostek-gfx/ranny/biodro2.bmp"
        Lecistopa          = "gostek-gfx/lecistopa.bmp"
        Lecistopa2         = "gostek-gfx/lecistopa2.bmp"

        // Gostek Team2 list. Keep it next to the non-team2 list.

        Team2Stopa         = "gostek-gfx/team2/stopa.bmp"
        Team2Stopa2        = "gostek-gfx/team2/stopa2.bmp"
        Team2Noga          = "gostek-gfx/team2/noga.bmp"
        Team2Noga2         = "gostek-gfx/team2/noga2.bmp"
        Team2Udo           = "gostek-gfx/team2/udo.bmp"
        Team2Udo2          = "gostek-gfx/team2/udo2.bmp"
        Team2Biodro        = "gostek-gfx/team2/biodro.bmp"
        Team2Biodro2       = "gostek-gfx/team2/biodro2.bmp"
        Team2Klata         = "gostek-gfx/team2/klata.bmp"
        Team2Klata2        = "gostek-gfx/team2/klata2.bmp"
        Team2Morda         = "gostek-gfx/team2/morda.bmp"
        Team2Morda2        = "gostek-gfx/team2/morda2.bmp"
        Team2Ramie         = "gostek-gfx/team2/ramie.bmp"
        Team2Ramie2        = "gostek-gfx/team2/ramie2.bmp"
        Team2Reka          = "gostek-gfx/team2/reka.bmp"
        Team2Reka2         = "gostek-gfx/team2/reka2.bmp"
        Team2Dlon          = "gostek-gfx/team2/dlon.bmp"
        Team2Dlon2         = "gostek-gfx/team2/dlon2.bmp"
        Team2Lancuch       = "gostek-gfx/team2/lancuch.bmp"
        Team2Helm          = "gostek-gfx/team2/helm.bmp"
        Team2Helm2         = "gostek-gfx/team2/helm2.bmp"
        Team2Badge         = "gostek-gfx/team2/badge.bmp"
        Team2Badge2        = "gostek-gfx/team2/badge2.bmp"
        Team2Cygaro        = "gostek-gfx/team2/cygaro.bmp"
        Team2Cygaro2       = "gostek-gfx/team2/cygaro2.bmp"
        Team2Metal         = "gostek-gfx/team2/metal.bmp"
        Team2Metal2        = "gostek-gfx/team2/metal2.bmp"
        Team2Zloto         = "gostek-gfx/team2/zloto.bmp"
        Team2Zloto2        = "gostek-gfx/team2/zloto2.bmp"
        Team2Zlotylancuch  = "gostek-gfx/team2/zlotylancuch.bmp"
        Team2Kap           = "gostek-gfx/team2/kap.bmp"
        Team2Kap2          = "gostek-gfx/team2/kap2.bmp"
        Team2Dred          = "gostek-gfx/team2/dred.bmp"
        Team2Hair1         = "gostek-gfx/team2/hair1.bmp"
        Team2Hair12        = "gostek-gfx/team2/hair12.bmp"
        Team2Hair2         = "gostek-gfx/team2/hair2.bmp"
        Team2Hair22        = "gostek-gfx/team2/hair22.bmp"
        Team2Hair3         = "gostek-gfx/team2/hair3.bmp"
        Team2Hair32        = "gostek-gfx/team2/hair32.bmp"
        Team2Hair4         = "gostek-gfx/team2/hair4.bmp"
        Team2Hair42        = "gostek-gfx/team2/hair42.bmp"
        Team2Kamizelka     = "gostek-gfx/team2/kamizelka.bmp"
        Team2Kamizelka2    = "gostek-gfx/team2/kamizelka2.bmp"
        Team2RannyKlata    = "gostek-gfx/team2/ranny/klata.bmp"
        Team2RannyKlata2   = "gostek-gfx/team2/ranny/klata2.bmp"
        Team2RannyMorda    = "gostek-gfx/team2/ranny/morda.bmp"
        Team2RannyMorda2   = "gostek-gfx/team2/ranny/morda2.bmp"
        Team2RannyNoga     = "gostek-gfx/team2/ranny/noga.bmp"
        Team2RannyNoga2    = "gostek-gfx/team2/ranny/noga2.bmp"
        Team2RannyRamie    = "gostek-gfx/team2/ranny/ramie.bmp"
        Team2RannyRamie2   = "gostek-gfx/team2/ranny/ramie2.bmp"
        Team2RannyReka     = "gostek-gfx/team2/ranny/reka.bmp"
        Team2RannyReka2    = "gostek-gfx/team2/ranny/reka2.bmp"
        Team2RannyUdo      = "gostek-gfx/team2/ranny/udo.bmp"
        Team2RannyUdo2     = "gostek-gfx/team2/ranny/udo2.bmp"
        Team2RannyBiodro   = "gostek-gfx/team2/ranny/biodro.bmp"
        Team2RannyBiodro2  = "gostek-gfx/team2/ranny/biodro2.bmp"
        Team2Lecistopa     = "gostek-gfx/team2/lecistopa.bmp"
        Team2Lecistopa2    = "gostek-gfx/team2/lecistopa2.bmp"

        // Preserve order of these parachute textures.

        ParaRope           = "gostek-gfx/para-rope.bmp"
        Para               = "gostek-gfx/para.bmp"
        Para2              = "gostek-gfx/para2.bmp"
    }

    // The range Shell to M2Stat is checked for size restriction too, so
    // keep that range together.

    Weapon {
        Shell              = "weapons-gfx/shell.bmp"
        Bullet             = "weapons-gfx/bullet.bmp"
        Smudge             = "weapons-gfx/smudge.bmp"
        Missile            = "weapons-gfx/missile.bmp"
        Cluster            = "weapons-gfx/cluster.bmp"
        ClusterGrenade     = "weapons-gfx/cluster-grenade.bmp"
        FragGrenade        = "weapons-gfx/frag-grenade.bmp"
        Ak74               = "weapons-gfx/ak74.bmp"
        Ak742              = "weapons-gfx/ak74-2.bmp"
        Ak74Clip           = "weapons-gfx/ak74-clip.bmp"
        Ak74Clip2          = "weapons-gfx/ak74-clip2.bmp"
        Ak74Shell          = "weapons-gfx/ak74-shell.bmp"
        Ak74Bullet         = "weapons-gfx/ak74-bullet.bmp"
        Ak74Fire           = "weapons-gfx/ak74-fire.bmp"
        Minimi             = "weapons-gfx/m249.bmp"
        Minimi2            = "weapons-gfx/m249-2.bmp"
        MinimiClip         = "weapons-gfx/m249-clip.bmp"
        MinimiClip2        = "weapons-gfx/m249-clip2.bmp"
        MinimiShell        = "weapons-gfx/m249-shell.bmp"
        MinimiBullet       = "weapons-gfx/m249-bullet.bmp"
        MinimiFire         = "weapons-gfx/m249-fire.bmp"
        Ruger              = "weapons-gfx/ruger77.bmp"
        Ruger2             = "weapons-gfx/ruger77-2.bmp"
        RugerShell         = "weapons-gfx/ruger77-shell.bmp"
        RugerBullet        = "weapons-gfx/ruger77-bullet.bmp"
        RugerFire          = "weapons-gfx/ruger77-fire.bmp"
        Mp5                = "weapons-gfx/mp5.bmp"
        Mp52               = "weapons-gfx/mp5-2.bmp"
        Mp5Clip            = "weapons-gfx/mp5-clip.bmp"
        Mp5Clip2           = "weapons-gfx/mp5-clip2.bmp"
        Mp5Shell           = "weapons-gfx/mp5-shell.bmp"
        Mp5Bullet          = "weapons-gfx/mp5-bullet.bmp"
        Mp5Fire            = "weapons-gfx/mp5-fire.bmp"
        Spas               = "weapons-gfx/spas12.bmp"
        Spas2              = "weapons-gfx/spas12-2.bmp"
        SpasShell          = "weapons-gfx/spas12-shell.bmp"
        SpasBullet         = "weapons-gfx/spas12-bullet.bmp"
        SpasFire           = "weapons-gfx/spas12-fire.bmp"
        M79                = "weapons-gfx/m79.bmp"
        M792               = "weapons-gfx/m79-2.bmp"
        M79Clip            = "weapons-gfx/m79-clip.bmp"
        M79Clip2           = "weapons-gfx/m79-clip2.bmp"
        M79Shell           = "weapons-gfx/m79-shell.bmp"
        M79Bullet          = "weapons-gfx/m79-bullet.bmp"
        M79Fire            = "weapons-gfx/m79-fire.bmp"
        Deagles            = "weapons-gfx/deserteagle.bmp"
        Deagles2           = "weapons-gfx/deserteagle-2.bmp"
        NDeagles           = "weapons-gfx/n-deserteagle.bmp"
        NDeagles2          = "weapons-gfx/n-deserteagle-2.bmp"
        DeaglesClip        = "weapons-gfx/deserteagle-clip.bmp"
        DeaglesClip2       = "weapons-gfx/deserteagle-clip2.bmp"
        DeaglesShell       = "weapons-gfx/eagles-shell.bmp"
        DeaglesBullet      = "weapons-gfx/eagles-bullet.bmp"
        DeaglesFire        = "weapons-gfx/eagles-fire.bmp"
        Steyr              = "weapons-gfx/steyraug.bmp"
        Steyr2             = "weapons-gfx/steyraug-2.bmp"
        SteyrClip          = "weapons-gfx/steyraug-clip.bmp"
        SteyrClip2         = "weapons-gfx/steyraug-clip2.bmp"
        SteyrShell         = "weapons-gfx/steyraug-shell.bmp"
        SteyrBullet        = "weapons-gfx/steyraug-bullet.bmp"
        SteyrFire          = "weapons-gfx/steyraug-fire.bmp"
        Barrett            = "weapons-gfx/barretm82.bmp"
        Barrett2           = "weapons-gfx/barretm82-2.bmp"
        BarrettClip        = "weapons-gfx/barretm82-clip.bmp"
        BarrettClip2       = "weapons-gfx/barretm82-clip2.bmp"
        BarrettShell       = "weapons-gfx/barretm82-shell.bmp"
        BarrettBullet      = "weapons-gfx/barretm82-bullet.bmp"
        BarrettFire        = "weapons-gfx/barret-fire.bmp"
        Minigun            = "weapons-gfx/minigun.bmp"
        Minigun2           = "weapons-gfx/minigun-2.bmp"
        MinigunClip        = "weapons-gfx/minigun-clip.bmp"
        MinigunShell       = "weapons-gfx/minigun-shell.bmp"
        MinigunBullet      = "weapons-gfx/minigun-bullet.bmp"
        MinigunFire        = "weapons-gfx/minigun-fire.bmp"
        Socom              = "weapons-gfx/colt1911.bmp"
        Socom2             = "weapons-gfx/colt1911-2.bmp"
        NSocom             = "weapons-gfx/n-colt1911.bmp"
        NSocom2            = "weapons-gfx/n-colt1911-2.bmp"
        SocomClip          = "weapons-gfx/colt1911-clip.bmp"
        SocomClip2         = "weapons-gfx/colt1911-clip2.bmp"
        ColtShell          = "weapons-gfx/colt-shell.bmp"
        ColtBullet         = "weapons-gfx/colt-bullet.bmp"
        SocomFire          = "weapons-gfx/colt1911-fire.bmp"
        Bow                = "weapons-gfx/bow.bmp"
        Bow2               = "weapons-gfx/bow-2.bmp"
        BowS               = "weapons-gfx/bow-s.bmp"
        BowA               = "weapons-gfx/bow-a.bmp"
        NBow               = "weapons-gfx/n-bow.bmp"
        NBow2              = "weapons-gfx/n-bow-2.bmp"
        Arrow              = "weapons-gfx/arrow.bmp"
        BowFire            = "weapons-gfx/bow-fire.bmp"
        Flamer             = "weapons-gfx/flamer.bmp"
        Flamer2            = "weapons-gfx/flamer-2.bmp"
        FlamerFire         = "weapons-gfx/flamer-fire.bmp"
        Knife              = "weapons-gfx/knife.bmp"
        Knife2             = "weapons-gfx/knife2.bmp"
        Chainsaw           = "weapons-gfx/chainsaw.bmp"
        Chainsaw2          = "weapons-gfx/chainsaw2.bmp"
        ChainsawFire       = "weapons-gfx/chainsaw-fire.bmp"
        Law                = "weapons-gfx/law.bmp"
        Law2               = "weapons-gfx/law-2.bmp"
        LawFire            = "weapons-gfx/law-fire.bmp"
        M2                 = "weapons-gfx/m2.bmp"
        M22                = "weapons-gfx/m2-2.bmp"
        M2Stat             = "weapons-gfx/m2-stat.bmp"
    }

    // Preserve order of:
    // - ExplosionExplode1 to ExplosionExplode16
    // - ExplosionSmoke1 to Minismoke
    // - FlamesExplode1 to FlamesExplode16

    Spark {
        Smoke              = "sparks-gfx/smoke.bmp"
        Lilfire            = "sparks-gfx/lilfire.bmp"
        Odprysk            = "sparks-gfx/odprysk.bmp"
        Blood              = "sparks-gfx/blood.bmp"
        ExplosionExplode1  = "sparks-gfx/explosion/explode1.bmp"
        ExplosionExplode2  = "sparks-gfx/explosion/explode2.bmp"
        ExplosionExplode3  = "sparks-gfx/explosion/explode3.bmp"
        ExplosionExplode4  = "sparks-gfx/explosion/explode4.bmp"
        ExplosionExplode5  = "sparks-gfx/explosion/explode5.bmp"
        ExplosionExplode6  = "sparks-gfx/explosion/explode6.bmp"
        ExplosionExplode7  = "sparks-gfx/explosion/explode7.bmp"
        ExplosionExplode8  = "sparks-gfx/explosion/explode8.bmp"
        ExplosionExplode9  = "sparks-gfx/explosion/explode9.bmp"
        ExplosionExplode10 = "sparks-gfx/explosion/explode10.bmp"
        ExplosionExplode11 = "sparks-gfx/explosion/explode11.bmp"
        ExplosionExplode12 = "sparks-gfx/explosion/explode12.bmp"
        ExplosionExplode13 = "sparks-gfx/explosion/explode13.bmp"
        ExplosionExplode14 = "sparks-gfx/explosion/explode14.bmp"
        ExplosionExplode15 = "sparks-gfx/explosion/explode15.bmp"
        ExplosionExplode16 = "sparks-gfx/explosion/explode16.bmp"
        Bigsmoke           = "sparks-gfx/bigsmoke.bmp"
        Spawnspark         = "sparks-gfx/spawnspark.bmp"
        Pin                = "sparks-gfx/pin.bmp"
        Lilsmoke           = "sparks-gfx/lilsmoke.bmp"
        Stuff              = "sparks-gfx/stuff.bmp"
        Cygaro             = "sparks-gfx/cygaro.bmp"
        Plomyk             = "sparks-gfx/plomyk.bmp"
        Blacksmoke         = "sparks-gfx/blacksmoke.bmp"
        Rain               = "sparks-gfx/rain.bmp"
        Sand               = "sparks-gfx/sand.bmp"
        Odlamek1           = "sparks-gfx/odlamek1.bmp"
        Odlamek2           = "sparks-gfx/odlamek2.bmp"
        Odlamek3           = "sparks-gfx/odlamek3.bmp"
        Odlamek4           = "sparks-gfx/odlamek4.bmp"
        Skrawek            = "sparks-gfx/skrawek.bmp"
        Puff               = "sparks-gfx/puff.bmp"
        Snow               = "sparks-gfx/snow.bmp"
        ExplosionSmoke1    = "sparks-gfx/explosion/smoke1.bmp"
        ExplosionSmoke2    = "sparks-gfx/explosion/smoke2.bmp"
        ExplosionSmoke3    = "sparks-gfx/explosion/smoke3.bmp"
        ExplosionSmoke4    = "sparks-gfx/explosion/smoke4.bmp"
        ExplosionSmoke5    = "sparks-gfx/explosion/smoke5.bmp"
        ExplosionSmoke6    = "sparks-gfx/explosion/smoke6.bmp"
        ExplosionSmoke7    = "sparks-gfx/explosion/smoke7.bmp"
        ExplosionSmoke8    = "sparks-gfx/explosion/smoke8.bmp"
        ExplosionSmoke9    = "sparks-gfx/explosion/smoke9.bmp"
        Splat              = "sparks-gfx/splat.bmp"
        Minismoke          = "sparks-gfx/minismoke.bmp"
        Bigsmoke2          = "sparks-gfx/bigsmoke2.bmp"
        Jetfire            = "sparks-gfx/jetfire.bmp"
        Lilblood           = "sparks-gfx/lilblood.bmp"
        FlamesExplode1     = "sparks-gfx/flames/explode1.bmp"
        FlamesExplode2     = "sparks-gfx/flames/explode2.bmp"
        FlamesExplode3     = "sparks-gfx/flames/explode3.bmp"
        FlamesExplode4     = "sparks-gfx/flames/explode4.bmp"
        FlamesExplode5     = "sparks-gfx/flames/explode5.bmp"
        FlamesExplode6     = "sparks-gfx/flames/explode6.bmp"
        FlamesExplode7     = "sparks-gfx/flames/explode7.bmp"
        FlamesExplode8     = "sparks-gfx/flames/explode8.bmp"
        FlamesExplode9     = "sparks-gfx/flames/explode9.bmp"
        FlamesExplode10    = "sparks-gfx/flames/explode10.bmp"
        FlamesExplode11    = "sparks-gfx/flames/explode11.bmp"
        FlamesExplode12    = "sparks-gfx/flames/explode12.bmp"
        FlamesExplode13    = "sparks-gfx/flames/explode13.bmp"
        FlamesExplode14    = "sparks-gfx/flames/explode14.bmp"
        FlamesExplode15    = "sparks-gfx/flames/explode15.bmp"
        FlamesExplode16    = "sparks-gfx/flames/explode16.bmp"
    }

    Object {
        Flag               = "textures/objects/flag.bmp"
        Infflag            = "textures/objects/infflag.bmp"
        Medikit            = "textures/objects/medikit.bmp"
        Grenadekit         = "textures/objects/grenadekit.bmp"
        Flamerkit          = "textures/objects/flamerkit.bmp"
        Predatorkit        = "textures/objects/predatorkit.bmp"
        Vestkit            = "textures/objects/vestkit.bmp"
        Berserkerkit       = "textures/objects/berserkerkit.bmp"
        Clusterkit         = "textures/objects/clusterkit.bmp"
        Ilum               = "objects-gfx/ilum.bmp"
        FlagHandle         = "objects-gfx/flag.bmp"
    }

    // Preserve order of Guns*

    Interface {
        Sight              = "interface-gfx/sight.bmp"
        GunsDeagles        = "interface-gfx/guns/1.bmp"
        GunsMp5            = "interface-gfx/guns/2.bmp"
        GunsAk74           = "interface-gfx/guns/3.bmp"
        GunsSteyr          = "interface-gfx/guns/4.bmp"
        GunsSpas           = "interface-gfx/guns/5.bmp"
        GunsRuger          = "interface-gfx/guns/6.bmp"
        GunsM79            = "interface-gfx/guns/7.bmp"
        GunsBarrett        = "interface-gfx/guns/8.bmp"
        GunsMinimi         = "interface-gfx/guns/9.bmp"
        GunsMinigun        = "interface-gfx/guns/0.bmp"
        GunsSocom          = "interface-gfx/guns/10.bmp"
        GunsKnife          = "interface-gfx/guns/knife.bmp"
        GunsChainsaw       = "interface-gfx/guns/chainsaw.bmp"
        GunsLaw            = "interface-gfx/guns/law.bmp"
        GunsFlamer         = "interface-gfx/guns/flamer.bmp"
        GunsBow            = "interface-gfx/guns/bow.bmp"
        GunsFist           = "interface-gfx/guns/fist.bmp"
        GunsM2             = "interface-gfx/guns/m2.bmp"
        Star               = "interface-gfx/star.bmp"
        Smalldot           = "interface-gfx/smalldot.bmp"
        Deaddot            = "interface-gfx/deaddot.bmp"
        Mute               = "interface-gfx/mute.bmp"
        Prot               = "interface-gfx/prot.png"
        Scroll             = "interface-gfx/scroll.png"
        Bot                = "interface-gfx/bot.bmp"
        Cursor             = "interface-gfx/cursor.bmp"
        Health             = "interface-gfx/health.bmp"
        Ammo               = "interface-gfx/ammo.bmp"
        Jet                = "interface-gfx/jet.bmp"
        HealthBar          = "interface-gfx/health-bar.bmp"
        JetBar             = "interface-gfx/jet-bar.bmp"
        ReloadBar          = "interface-gfx/reload-bar.bmp"
        Back               = "interface-gfx/back.bmp"
        Overlay            = "interface-gfx/overlay.bmp"
        Nade               = "interface-gfx/nade.bmp"
        Noflag             = "interface-gfx/noflag.bmp"
        Flag               = "interface-gfx/flag.bmp"
        ClusterNade        = "interface-gfx/cluster-nade.bmp"
        Dot                = "interface-gfx/dot.bmp"
        FireBar            = "interface-gfx/fire-bar.bmp"
        FireBarR           = "interface-gfx/fire-bar-r.bmp"
        VestBar            = "interface-gfx/vest-bar.bmp"
        Menucursor         = "interface-gfx/menucursor.bmp"
        Arrow              = "interface-gfx/arrow.bmp"
        TitleL             = "interface-gfx/title-l.bmp"
        TitleR             = "interface-gfx/title-r.bmp"
    }
}

gostek_parts! {
    SecondaryDeagles       = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMp5           = Sprite(Weapon::Mp5),             Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryAk74          = Sprite(Weapon::Ak74),            Point( 5, 10), Center( 0.300,  0.250), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySteyr         = Sprite(Weapon::Steyr),           Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySpas          = Sprite(Weapon::Spas),            Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryRuger         = Sprite(Weapon::Ruger),           Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryM79           = Sprite(Weapon::M79),             Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryBarrett       = Sprite(Weapon::Barrett),         Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMinimi        = Sprite(Weapon::Minimi),          Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMinigun       = Sprite(Weapon::Minigun),         Point( 5, 10), Center( 0.200,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySocom         = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryKnife         = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryChainsaw      = Sprite(Weapon::Chainsaw),        Point( 5, 10), Center( 0.250,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryLaw           = Sprite(Weapon::Law),             Point( 5, 10), Center( 0.300,  0.450), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryFlamebow      = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryBow           = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryFlamer        = Sprite(Weapon::Flamer),          Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    LeftThigh              = Sprite(Gostek::Udo),             Point( 6,  3), Center( 0.200,  0.500), Show(true),  Flip(true),  Team(true),  Flex(5.0), Color(Pants),     Alpha(Base )
    LeftThighDmg           = Sprite(Gostek::RannyUdo),        Point( 6,  3), Center( 0.200,  0.500), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    LeftFoot               = Sprite(Gostek::Stopa),           Point( 2, 18), Center( 0.350,  0.350), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    LeftJetfoot            = Sprite(Gostek::Lecistopa),       Point( 2, 18), Center( 0.350,  0.350), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    LeftLowerleg           = Sprite(Gostek::Noga),            Point( 3,  2), Center( 0.150,  0.550), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Pants),     Alpha(Base )
    LeftLowerlegDmg        = Sprite(Gostek::RannyNoga),       Point( 3,  2), Center( 0.150,  0.550), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    LeftArm                = Sprite(Gostek::Ramie),           Point(11, 14), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    LeftArmDmg             = Sprite(Gostek::RannyRamie),      Point(11, 14), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    LeftForearm            = Sprite(Gostek::Reka),            Point(14, 15), Center( 0.000,  0.500), Show(true),  Flip(false), Team(true),  Flex(5.0), Color(Main),      Alpha(Base )
    LeftForearmDmg         = Sprite(Gostek::RannyReka),       Point(14, 15), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    LeftHand               = Sprite(Gostek::Dlon),            Point(15, 19), Center( 0.000,  0.400), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    GrabbedHelmet          = Sprite(Gostek::Helm),            Point(15, 19), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    GrabbedHat             = Sprite(Gostek::Kap),             Point(15, 19), Center( 0.100,  0.400), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RightThigh             = Sprite(Gostek::Udo),             Point( 5,  4), Center( 0.200,  0.650), Show(true),  Flip(true),  Team(true),  Flex(5.0), Color(Pants),     Alpha(Base )
    RightThighDmg          = Sprite(Gostek::RannyUdo),        Point( 5,  4), Center( 0.200,  0.650), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    RightFoot              = Sprite(Gostek::Stopa),           Point( 1, 17), Center( 0.350,  0.350), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    RightJetfoot           = Sprite(Gostek::Lecistopa),       Point( 1, 17), Center( 0.350,  0.350), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    RightLowerleg          = Sprite(Gostek::Noga),            Point( 4,  1), Center( 0.150,  0.550), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Pants),     Alpha(Base )
    RightLowerlegDmg       = Sprite(Gostek::RannyNoga),       Point( 4,  1), Center( 0.150,  0.550), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Chest                  = Sprite(Gostek::Klata),           Point(10, 11), Center( 0.100,  0.300), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    Vest                   = Sprite(Gostek::Kamizelka),       Point(10, 11), Center( 0.100,  0.300), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    ChestDmg               = Sprite(Gostek::RannyKlata),      Point(10, 11), Center( 0.100,  0.300), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Hip                    = Sprite(Gostek::Biodro),          Point( 5,  6), Center( 0.250,  0.600), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    HipDmg                 = Sprite(Gostek::RannyBiodro),     Point( 5,  6), Center( 0.250,  0.600), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Head                   = Sprite(Gostek::Morda),           Point( 9, 12), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    HeadDmg                = Sprite(Gostek::RannyMorda),      Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Headblood), Alpha(Blood)
    HeadDead               = Sprite(Gostek::Morda),           Point( 9, 12), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    HeadDeadDmg            = Sprite(Gostek::RannyMorda),      Point( 9, 12), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Headblood), Alpha(Blood)
    MrT                    = Sprite(Gostek::Hair3),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    Helmet                 = Sprite(Gostek::Helm),            Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    Hat                    = Sprite(Gostek::Kap),             Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RamboBadge             = Sprite(Gostek::Badge),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    HairDreadlocks         = Sprite(Gostek::Hair1),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock1         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.000,  1.220), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock2         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock3         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.040, -0.300), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock4         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.000, -0.900), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock5         = Sprite(Gostek::Dred),            Point(23, 24), Center(-0.200, -1.350), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairPunk               = Sprite(Gostek::Hair2),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairNormal             = Sprite(Gostek::Hair4),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    Cigar                  = Sprite(Gostek::Cygaro),          Point( 9, 12), Center(-0.125,  0.400), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Cygar),     Alpha(Base )
    SilverLChain           = Sprite(Gostek::Lancuch),         Point(10, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    SilverRChain           = Sprite(Gostek::Lancuch),         Point(11, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    SilverPendant          = Sprite(Gostek::Metal),           Point(22, 21), Center( 0.500,  0.700), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenLChain           = Sprite(Gostek::Zlotylancuch),    Point(10, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenRChain           = Sprite(Gostek::Zlotylancuch),    Point(11, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenPendant          = Sprite(Gostek::Zloto),           Point(22, 21), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    FragGrenade1           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade2           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade3           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade4           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade5           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade1        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade2        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade3        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade4        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade5        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    PrimaryDeagles         = Sprite(Weapon::Deagles),         Point(16, 15), Center( 0.100,  0.800), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryDeaglesClip     = Sprite(Weapon::DeaglesClip),     Point(16, 15), Center( 0.100,  0.800), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryDeaglesFire     = Sprite(Weapon::DeaglesFire),     Point(16, 15), Center(-0.500,  1.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5             = Sprite(Weapon::Mp5),             Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5Clip         = Sprite(Weapon::Mp5Clip),         Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5Fire         = Sprite(Weapon::Mp5Fire),         Point(16, 15), Center( -0.65,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74            = Sprite(Weapon::Ak74),            Point(16, 15), Center( 0.150,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74Clip        = Sprite(Weapon::Ak74Clip),        Point(16, 15), Center( 0.150,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74Fire        = Sprite(Weapon::Ak74Fire),        Point(16, 15), Center( -0.37,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyr           = Sprite(Weapon::Steyr),           Point(16, 15), Center( 0.200,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyrClip       = Sprite(Weapon::SteyrClip),       Point(16, 15), Center( 0.200,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyrFire       = Sprite(Weapon::SteyrFire),       Point(16, 15), Center( -0.24,  0.750), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpas            = Sprite(Weapon::Spas),            Point(16, 15), Center( 0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpasClip        = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpasFire        = Sprite(Weapon::SpasFire),        Point(16, 15), Center(-0.200,  0.900), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRuger           = Sprite(Weapon::Ruger),           Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRugerClip       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRugerFire       = Sprite(Weapon::RugerFire),       Point(16, 15), Center( -0.35,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79             = Sprite(Weapon::M79),             Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79Clip         = Sprite(Weapon::M79Clip),         Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79Fire         = Sprite(Weapon::M79Fire),         Point(16, 15), Center(-0.400,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrett         = Sprite(Weapon::Barrett),         Point(16, 15), Center( 0.150,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrettClip     = Sprite(Weapon::BarrettClip),     Point(16, 15), Center( 0.150,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrettFire     = Sprite(Weapon::BarrettFire),     Point(16, 15), Center( -0.15,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimi          = Sprite(Weapon::Minimi),          Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimiClip      = Sprite(Weapon::MinimiClip),      Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimiFire      = Sprite(Weapon::MinimiFire),      Point(16, 15), Center(-0.200,  0.900), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigunClip     = Sprite(Weapon::MinigunClip),     Point( 8,  7), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigun         = Sprite(Weapon::Minigun),         Point(16, 15), Center( 0.050,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigunFire     = Sprite(Weapon::MinigunFire),     Point(16, 15), Center(-0.200,  0.450), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocom           = Sprite(Weapon::Socom),           Point(16, 15), Center( 0.200,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocomClip       = Sprite(Weapon::SocomClip),       Point(16, 15), Center( 0.200,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocomFire       = Sprite(Weapon::SocomFire),       Point(16, 15), Center( -0.24,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnife           = Sprite(Weapon::Knife),           Point(16, 20), Center(-0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnifeClip       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnifeFire       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsaw        = Sprite(Weapon::Chainsaw),        Point(16, 15), Center( 0.100,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsawClip    = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsawFire    = Sprite(Weapon::ChainsawFire),    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLaw             = Sprite(Weapon::Law),             Point(16, 15), Center( 0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLawClip         = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLawFire         = Sprite(Weapon::LawFire),         Point(16, 15), Center(-0.100,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBow             = Sprite(Weapon::Bow),             Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowArrow        = Sprite(Weapon::BowA),            Point(16, 15), Center( 0.000,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowString       = Sprite(Weapon::BowS),            Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowReload       = Sprite(Weapon::Bow),             Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowArrowReload  = Sprite(Weapon::Arrow),           Point(16, 20), Center( 0.000,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowStringReload = Sprite(Weapon::BowS),            Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowFire         = Sprite(Weapon::BowFire),         Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamer          = Sprite(Weapon::Flamer),          Point(16, 15), Center( 0.200,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamerClip      = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamerFire      = Sprite(Weapon::FlamerFire),      Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    RightArm               = Sprite(Gostek::Ramie),           Point(10, 13), Center( 0.000,  0.600), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RightArmDmg            = Sprite(Gostek::RannyRamie),      Point(10, 13), Center(-0.100,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    RightForearm           = Sprite(Gostek::Reka),            Point(13, 16), Center( 0.000,  0.600), Show(true),  Flip(false), Team(true),  Flex(5.0), Color(Main),      Alpha(Base )
    RightForearmDmg        = Sprite(Gostek::RannyReka),       Point(13, 16), Center( 0.000,  0.600), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    RightHand              = Sprite(Gostek::Dlon),            Point(16, 20), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
}
