use super::*;

include!("sprite_data_macro.rs");

// Note: images that have a "2" version go together (opposite gostek direction).

sprites! {
    // The order of the gostek images must match the order of the Team2 versions
    // listed below. Keep both lists together, the range Gostek::Stopa to
    // Gostek::Team2Lecistopa2 is checked for a size restriction.

    Gostek {
        Stopa              = r"gostek-gfx\stopa.bmp"
        Stopa2             = r"gostek-gfx\stopa2.bmp"
        Noga               = r"gostek-gfx\noga.bmp"
        Noga2              = r"gostek-gfx\noga2.bmp"
        Udo                = r"gostek-gfx\udo.bmp"
        Udo2               = r"gostek-gfx\udo2.bmp"
        Biodro             = r"gostek-gfx\biodro.bmp"
        Biodro2            = r"gostek-gfx\biodro2.bmp"
        Klata              = r"gostek-gfx\klata.bmp"
        Klata2             = r"gostek-gfx\klata2.bmp"
        Morda              = r"gostek-gfx\morda.bmp"
        Morda2             = r"gostek-gfx\morda2.bmp"
        Ramie              = r"gostek-gfx\ramie.bmp"
        Ramie2             = r"gostek-gfx\ramie2.bmp"
        Reka               = r"gostek-gfx\reka.bmp"
        Reka2              = r"gostek-gfx\reka2.bmp"
        Dlon               = r"gostek-gfx\dlon.bmp"
        Dlon2              = r"gostek-gfx\dlon2.bmp"
        Lancuch            = r"gostek-gfx\lancuch.bmp"
        Helm               = r"gostek-gfx\helm.bmp"
        Helm2              = r"gostek-gfx\helm2.bmp"
        Badge              = r"gostek-gfx\badge.bmp"
        Badge2             = r"gostek-gfx\badge2.bmp"
        Cygaro             = r"gostek-gfx\cygaro.bmp"
        Cygaro2            = r"gostek-gfx\cygaro2.bmp"
        Metal              = r"gostek-gfx\metal.bmp"
        Metal2             = r"gostek-gfx\metal2.bmp"
        Zloto              = r"gostek-gfx\zloto.bmp"
        Zloto2             = r"gostek-gfx\zloto2.bmp"
        Zlotylancuch       = r"gostek-gfx\zlotylancuch.bmp"
        Kap                = r"gostek-gfx\kap.bmp"
        Kap2               = r"gostek-gfx\kap2.bmp"
        Dred               = r"gostek-gfx\dred.bmp"
        Hair1              = r"gostek-gfx\hair1.bmp"
        Hair12             = r"gostek-gfx\hair12.bmp"
        Hair2              = r"gostek-gfx\hair2.bmp"
        Hair22             = r"gostek-gfx\hair22.bmp"
        Hair3              = r"gostek-gfx\hair3.bmp"
        Hair32             = r"gostek-gfx\hair32.bmp"
        Hair4              = r"gostek-gfx\hair4.bmp"
        Hair42             = r"gostek-gfx\hair42.bmp"
        Kamizelka          = r"gostek-gfx\kamizelka.bmp"
        Kamizelka2         = r"gostek-gfx\kamizelka2.bmp"
        RannyKlata         = r"gostek-gfx\ranny\klata.bmp"
        RannyKlata2        = r"gostek-gfx\ranny\klata2.bmp"
        RannyMorda         = r"gostek-gfx\ranny\morda.bmp"
        RannyMorda2        = r"gostek-gfx\ranny\morda2.bmp"
        RannyNoga          = r"gostek-gfx\ranny\noga.bmp"
        RannyNoga2         = r"gostek-gfx\ranny\noga2.bmp"
        RannyRamie         = r"gostek-gfx\ranny\ramie.bmp"
        RannyRamie2        = r"gostek-gfx\ranny\ramie2.bmp"
        RannyReka          = r"gostek-gfx\ranny\reka.bmp"
        RannyReka2         = r"gostek-gfx\ranny\reka2.bmp"
        RannyUdo           = r"gostek-gfx\ranny\udo.bmp"
        RannyUdo2          = r"gostek-gfx\ranny\udo2.bmp"
        RannyBiodro        = r"gostek-gfx\ranny\biodro.bmp"
        RannyBiodro2       = r"gostek-gfx\ranny\biodro2.bmp"
        Lecistopa          = r"gostek-gfx\lecistopa.bmp"
        Lecistopa2         = r"gostek-gfx\lecistopa2.bmp"

        // Gostek Team2 list. Keep it next to the non-team2 list.

        Team2Stopa         = r"gostek-gfx\team2\stopa.bmp"
        Team2Stopa2        = r"gostek-gfx\team2\stopa2.bmp"
        Team2Noga          = r"gostek-gfx\team2\noga.bmp"
        Team2Noga2         = r"gostek-gfx\team2\noga2.bmp"
        Team2Udo           = r"gostek-gfx\team2\udo.bmp"
        Team2Udo2          = r"gostek-gfx\team2\udo2.bmp"
        Team2Biodro        = r"gostek-gfx\team2\biodro.bmp"
        Team2Biodro2       = r"gostek-gfx\team2\biodro2.bmp"
        Team2Klata         = r"gostek-gfx\team2\klata.bmp"
        Team2Klata2        = r"gostek-gfx\team2\klata2.bmp"
        Team2Morda         = r"gostek-gfx\team2\morda.bmp"
        Team2Morda2        = r"gostek-gfx\team2\morda2.bmp"
        Team2Ramie         = r"gostek-gfx\team2\ramie.bmp"
        Team2Ramie2        = r"gostek-gfx\team2\ramie2.bmp"
        Team2Reka          = r"gostek-gfx\team2\reka.bmp"
        Team2Reka2         = r"gostek-gfx\team2\reka2.bmp"
        Team2Dlon          = r"gostek-gfx\team2\dlon.bmp"
        Team2Dlon2         = r"gostek-gfx\team2\dlon2.bmp"
        Team2Lancuch       = r"gostek-gfx\team2\lancuch.bmp"
        Team2Helm          = r"gostek-gfx\team2\helm.bmp"
        Team2Helm2         = r"gostek-gfx\team2\helm2.bmp"
        Team2Badge         = r"gostek-gfx\team2\badge.bmp"
        Team2Badge2        = r"gostek-gfx\team2\badge2.bmp"
        Team2Cygaro        = r"gostek-gfx\team2\cygaro.bmp"
        Team2Cygaro2       = r"gostek-gfx\team2\cygaro2.bmp"
        Team2Metal         = r"gostek-gfx\team2\metal.bmp"
        Team2Metal2        = r"gostek-gfx\team2\metal2.bmp"
        Team2Zloto         = r"gostek-gfx\team2\zloto.bmp"
        Team2Zloto2        = r"gostek-gfx\team2\zloto2.bmp"
        Team2Zlotylancuch  = r"gostek-gfx\team2\zlotylancuch.bmp"
        Team2Kap           = r"gostek-gfx\team2\kap.bmp"
        Team2Kap2          = r"gostek-gfx\team2\kap2.bmp"
        Team2Dred          = r"gostek-gfx\team2\dred.bmp"
        Team2Hair1         = r"gostek-gfx\team2\hair1.bmp"
        Team2Hair12        = r"gostek-gfx\team2\hair12.bmp"
        Team2Hair2         = r"gostek-gfx\team2\hair2.bmp"
        Team2Hair22        = r"gostek-gfx\team2\hair22.bmp"
        Team2Hair3         = r"gostek-gfx\team2\hair3.bmp"
        Team2Hair32        = r"gostek-gfx\team2\hair32.bmp"
        Team2Hair4         = r"gostek-gfx\team2\hair4.bmp"
        Team2Hair42        = r"gostek-gfx\team2\hair42.bmp"
        Team2Kamizelka     = r"gostek-gfx\team2\kamizelka.bmp"
        Team2Kamizelka2    = r"gostek-gfx\team2\kamizelka2.bmp"
        Team2RannyKlata    = r"gostek-gfx\team2\ranny\klata.bmp"
        Team2RannyKlata2   = r"gostek-gfx\team2\ranny\klata2.bmp"
        Team2RannyMorda    = r"gostek-gfx\team2\ranny\morda.bmp"
        Team2RannyMorda2   = r"gostek-gfx\team2\ranny\morda2.bmp"
        Team2RannyNoga     = r"gostek-gfx\team2\ranny\noga.bmp"
        Team2RannyNoga2    = r"gostek-gfx\team2\ranny\noga2.bmp"
        Team2RannyRamie    = r"gostek-gfx\team2\ranny\ramie.bmp"
        Team2RannyRamie2   = r"gostek-gfx\team2\ranny\ramie2.bmp"
        Team2RannyReka     = r"gostek-gfx\team2\ranny\reka.bmp"
        Team2RannyReka2    = r"gostek-gfx\team2\ranny\reka2.bmp"
        Team2RannyUdo      = r"gostek-gfx\team2\ranny\udo.bmp"
        Team2RannyUdo2     = r"gostek-gfx\team2\ranny\udo2.bmp"
        Team2RannyBiodro   = r"gostek-gfx\team2\ranny\biodro.bmp"
        Team2RannyBiodro2  = r"gostek-gfx\team2\ranny\biodro2.bmp"
        Team2Lecistopa     = r"gostek-gfx\team2\lecistopa.bmp"
        Team2Lecistopa2    = r"gostek-gfx\team2\lecistopa2.bmp"

        // Preserve order of these parachute textures.

        ParaRope           = r"gostek-gfx\para-rope.bmp"
        Para               = r"gostek-gfx\para.bmp"
        Para2              = r"gostek-gfx\para2.bmp"
    }

    // The range Shell to M2Stat is checked for size restriction too, so
    // keep that range together.

    Weapon {
        Shell              = r"weapons-gfx\shell.bmp"
        Bullet             = r"weapons-gfx\bullet.bmp"
        Smudge             = r"weapons-gfx\smudge.bmp"
        Missile            = r"weapons-gfx\missile.bmp"
        Cluster            = r"weapons-gfx\cluster.bmp"
        ClusterGrenade     = r"weapons-gfx\cluster-grenade.bmp"
        FragGrenade        = r"weapons-gfx\frag-grenade.bmp"
        Ak74               = r"weapons-gfx\ak74.bmp"
        Ak742              = r"weapons-gfx\ak74-2.bmp"
        Ak74Clip           = r"weapons-gfx\ak74-clip.bmp"
        Ak74Clip2          = r"weapons-gfx\ak74-clip2.bmp"
        Ak74Shell          = r"weapons-gfx\ak74-shell.bmp"
        Ak74Bullet         = r"weapons-gfx\ak74-bullet.bmp"
        Ak74Fire           = r"weapons-gfx\ak74-fire.bmp"
        Minimi             = r"weapons-gfx\m249.bmp"
        Minimi2            = r"weapons-gfx\m249-2.bmp"
        MinimiClip         = r"weapons-gfx\m249-clip.bmp"
        MinimiClip2        = r"weapons-gfx\m249-clip2.bmp"
        MinimiShell        = r"weapons-gfx\m249-shell.bmp"
        MinimiBullet       = r"weapons-gfx\m249-bullet.bmp"
        MinimiFire         = r"weapons-gfx\m249-fire.bmp"
        Ruger              = r"weapons-gfx\ruger77.bmp"
        Ruger2             = r"weapons-gfx\ruger77-2.bmp"
        RugerShell         = r"weapons-gfx\ruger77-shell.bmp"
        RugerBullet        = r"weapons-gfx\ruger77-bullet.bmp"
        RugerFire          = r"weapons-gfx\ruger77-fire.bmp"
        Mp5                = r"weapons-gfx\mp5.bmp"
        Mp52               = r"weapons-gfx\mp5-2.bmp"
        Mp5Clip            = r"weapons-gfx\mp5-clip.bmp"
        Mp5Clip2           = r"weapons-gfx\mp5-clip2.bmp"
        Mp5Shell           = r"weapons-gfx\mp5-shell.bmp"
        Mp5Bullet          = r"weapons-gfx\mp5-bullet.bmp"
        Mp5Fire            = r"weapons-gfx\mp5-fire.bmp"
        Spas               = r"weapons-gfx\spas12.bmp"
        Spas2              = r"weapons-gfx\spas12-2.bmp"
        SpasShell          = r"weapons-gfx\spas12-shell.bmp"
        SpasBullet         = r"weapons-gfx\spas12-bullet.bmp"
        SpasFire           = r"weapons-gfx\spas12-fire.bmp"
        M79                = r"weapons-gfx\m79.bmp"
        M792               = r"weapons-gfx\m79-2.bmp"
        M79Clip            = r"weapons-gfx\m79-clip.bmp"
        M79Clip2           = r"weapons-gfx\m79-clip2.bmp"
        M79Shell           = r"weapons-gfx\m79-shell.bmp"
        M79Bullet          = r"weapons-gfx\m79-bullet.bmp"
        M79Fire            = r"weapons-gfx\m79-fire.bmp"
        Deagles            = r"weapons-gfx\deserteagle.bmp"
        Deagles2           = r"weapons-gfx\deserteagle-2.bmp"
        NDeagles           = r"weapons-gfx\n-deserteagle.bmp"
        NDeagles2          = r"weapons-gfx\n-deserteagle-2.bmp"
        DeaglesClip        = r"weapons-gfx\deserteagle-clip.bmp"
        DeaglesClip2       = r"weapons-gfx\deserteagle-clip2.bmp"
        DeaglesShell       = r"weapons-gfx\eagles-shell.bmp"
        DeaglesBullet      = r"weapons-gfx\eagles-bullet.bmp"
        DeaglesFire        = r"weapons-gfx\eagles-fire.bmp"
        Steyr              = r"weapons-gfx\steyraug.bmp"
        Steyr2             = r"weapons-gfx\steyraug-2.bmp"
        SteyrClip          = r"weapons-gfx\steyraug-clip.bmp"
        SteyrClip2         = r"weapons-gfx\steyraug-clip2.bmp"
        SteyrShell         = r"weapons-gfx\steyraug-shell.bmp"
        SteyrBullet        = r"weapons-gfx\steyraug-bullet.bmp"
        SteyrFire          = r"weapons-gfx\steyraug-fire.bmp"
        Barrett            = r"weapons-gfx\barretm82.bmp"
        Barrett2           = r"weapons-gfx\barretm82-2.bmp"
        BarrettClip        = r"weapons-gfx\barretm82-clip.bmp"
        BarrettClip2       = r"weapons-gfx\barretm82-clip2.bmp"
        BarrettShell       = r"weapons-gfx\barretm82-shell.bmp"
        BarrettBullet      = r"weapons-gfx\barretm82-bullet.bmp"
        BarrettFire        = r"weapons-gfx\barret-fire.bmp"
        Minigun            = r"weapons-gfx\minigun.bmp"
        Minigun2           = r"weapons-gfx\minigun-2.bmp"
        MinigunClip        = r"weapons-gfx\minigun-clip.bmp"
        MinigunShell       = r"weapons-gfx\minigun-shell.bmp"
        MinigunBullet      = r"weapons-gfx\minigun-bullet.bmp"
        MinigunFire        = r"weapons-gfx\minigun-fire.bmp"
        Socom              = r"weapons-gfx\colt1911.bmp"
        Socom2             = r"weapons-gfx\colt1911-2.bmp"
        NSocom             = r"weapons-gfx\n-colt1911.bmp"
        NSocom2            = r"weapons-gfx\n-colt1911-2.bmp"
        SocomClip          = r"weapons-gfx\colt1911-clip.bmp"
        SocomClip2         = r"weapons-gfx\colt1911-clip2.bmp"
        ColtShell          = r"weapons-gfx\colt-shell.bmp"
        ColtBullet         = r"weapons-gfx\colt-bullet.bmp"
        SocomFire          = r"weapons-gfx\colt1911-fire.bmp"
        Bow                = r"weapons-gfx\bow.bmp"
        Bow2               = r"weapons-gfx\bow-2.bmp"
        BowS               = r"weapons-gfx\bow-s.bmp"
        BowA               = r"weapons-gfx\bow-a.bmp"
        NBow               = r"weapons-gfx\n-bow.bmp"
        NBow2              = r"weapons-gfx\n-bow-2.bmp"
        Arrow              = r"weapons-gfx\arrow.bmp"
        BowFire            = r"weapons-gfx\bow-fire.bmp"
        Flamer             = r"weapons-gfx\flamer.bmp"
        Flamer2            = r"weapons-gfx\flamer-2.bmp"
        FlamerFire         = r"weapons-gfx\flamer-fire.bmp"
        Knife              = r"weapons-gfx\knife.bmp"
        Knife2             = r"weapons-gfx\knife2.bmp"
        Chainsaw           = r"weapons-gfx\chainsaw.bmp"
        Chainsaw2          = r"weapons-gfx\chainsaw2.bmp"
        ChainsawFire       = r"weapons-gfx\chainsaw-fire.bmp"
        Law                = r"weapons-gfx\law.bmp"
        Law2               = r"weapons-gfx\law-2.bmp"
        LawFire            = r"weapons-gfx\law-fire.bmp"
        M2                 = r"weapons-gfx\m2.bmp"
        M22                = r"weapons-gfx\m2-2.bmp"
        M2Stat             = r"weapons-gfx\m2-stat.bmp"
    }

    // Preserve order of:
    // - ExplosionExplode1 to ExplosionExplode16
    // - ExplosionSmoke1 to Minismoke
    // - FlamesExplode1 to FlamesExplode16

    Spark {
        Smoke              = r"sparks-gfx\smoke.bmp"
        Lilfire            = r"sparks-gfx\lilfire.bmp"
        Odprysk            = r"sparks-gfx\odprysk.bmp"
        Blood              = r"sparks-gfx\blood.bmp"
        ExplosionExplode1  = r"sparks-gfx\explosion\explode1.bmp"
        ExplosionExplode2  = r"sparks-gfx\explosion\explode2.bmp"
        ExplosionExplode3  = r"sparks-gfx\explosion\explode3.bmp"
        ExplosionExplode4  = r"sparks-gfx\explosion\explode4.bmp"
        ExplosionExplode5  = r"sparks-gfx\explosion\explode5.bmp"
        ExplosionExplode6  = r"sparks-gfx\explosion\explode6.bmp"
        ExplosionExplode7  = r"sparks-gfx\explosion\explode7.bmp"
        ExplosionExplode8  = r"sparks-gfx\explosion\explode8.bmp"
        ExplosionExplode9  = r"sparks-gfx\explosion\explode9.bmp"
        ExplosionExplode10 = r"sparks-gfx\explosion\explode10.bmp"
        ExplosionExplode11 = r"sparks-gfx\explosion\explode11.bmp"
        ExplosionExplode12 = r"sparks-gfx\explosion\explode12.bmp"
        ExplosionExplode13 = r"sparks-gfx\explosion\explode13.bmp"
        ExplosionExplode14 = r"sparks-gfx\explosion\explode14.bmp"
        ExplosionExplode15 = r"sparks-gfx\explosion\explode15.bmp"
        ExplosionExplode16 = r"sparks-gfx\explosion\explode16.bmp"
        Bigsmoke           = r"sparks-gfx\bigsmoke.bmp"
        Spawnspark         = r"sparks-gfx\spawnspark.bmp"
        Pin                = r"sparks-gfx\pin.bmp"
        Lilsmoke           = r"sparks-gfx\lilsmoke.bmp"
        Stuff              = r"sparks-gfx\stuff.bmp"
        Cygaro             = r"sparks-gfx\cygaro.bmp"
        Plomyk             = r"sparks-gfx\plomyk.bmp"
        Blacksmoke         = r"sparks-gfx\blacksmoke.bmp"
        Rain               = r"sparks-gfx\rain.bmp"
        Sand               = r"sparks-gfx\sand.bmp"
        Odlamek1           = r"sparks-gfx\odlamek1.bmp"
        Odlamek2           = r"sparks-gfx\odlamek2.bmp"
        Odlamek3           = r"sparks-gfx\odlamek3.bmp"
        Odlamek4           = r"sparks-gfx\odlamek4.bmp"
        Skrawek            = r"sparks-gfx\skrawek.bmp"
        Puff               = r"sparks-gfx\puff.bmp"
        Snow               = r"sparks-gfx\snow.bmp"
        ExplosionSmoke1    = r"sparks-gfx\explosion\smoke1.bmp"
        ExplosionSmoke2    = r"sparks-gfx\explosion\smoke2.bmp"
        ExplosionSmoke3    = r"sparks-gfx\explosion\smoke3.bmp"
        ExplosionSmoke4    = r"sparks-gfx\explosion\smoke4.bmp"
        ExplosionSmoke5    = r"sparks-gfx\explosion\smoke5.bmp"
        ExplosionSmoke6    = r"sparks-gfx\explosion\smoke6.bmp"
        ExplosionSmoke7    = r"sparks-gfx\explosion\smoke7.bmp"
        ExplosionSmoke8    = r"sparks-gfx\explosion\smoke8.bmp"
        ExplosionSmoke9    = r"sparks-gfx\explosion\smoke9.bmp"
        Splat              = r"sparks-gfx\splat.bmp"
        Minismoke          = r"sparks-gfx\minismoke.bmp"
        Bigsmoke2          = r"sparks-gfx\bigsmoke2.bmp"
        Jetfire            = r"sparks-gfx\jetfire.bmp"
        Lilblood           = r"sparks-gfx\lilblood.bmp"
        FlamesExplode1     = r"sparks-gfx\flames\explode1.bmp"
        FlamesExplode2     = r"sparks-gfx\flames\explode2.bmp"
        FlamesExplode3     = r"sparks-gfx\flames\explode3.bmp"
        FlamesExplode4     = r"sparks-gfx\flames\explode4.bmp"
        FlamesExplode5     = r"sparks-gfx\flames\explode5.bmp"
        FlamesExplode6     = r"sparks-gfx\flames\explode6.bmp"
        FlamesExplode7     = r"sparks-gfx\flames\explode7.bmp"
        FlamesExplode8     = r"sparks-gfx\flames\explode8.bmp"
        FlamesExplode9     = r"sparks-gfx\flames\explode9.bmp"
        FlamesExplode10    = r"sparks-gfx\flames\explode10.bmp"
        FlamesExplode11    = r"sparks-gfx\flames\explode11.bmp"
        FlamesExplode12    = r"sparks-gfx\flames\explode12.bmp"
        FlamesExplode13    = r"sparks-gfx\flames\explode13.bmp"
        FlamesExplode14    = r"sparks-gfx\flames\explode14.bmp"
        FlamesExplode15    = r"sparks-gfx\flames\explode15.bmp"
        FlamesExplode16    = r"sparks-gfx\flames\explode16.bmp"
    }

    Object {
        Flag               = r"textures\objects\flag.bmp"
        Infflag            = r"textures\objects\infflag.bmp"
        Medikit            = r"textures\objects\medikit.bmp"
        Grenadekit         = r"textures\objects\grenadekit.bmp"
        Flamerkit          = r"textures\objects\flamerkit.bmp"
        Predatorkit        = r"textures\objects\predatorkit.bmp"
        Vestkit            = r"textures\objects\vestkit.bmp"
        Berserkerkit       = r"textures\objects\berserkerkit.bmp"
        Clusterkit         = r"textures\objects\clusterkit.bmp"
        Ilum               = r"objects-gfx\ilum.bmp"
        FlagHandle         = r"objects-gfx\flag.bmp"
    }

    // Preserve order of Guns*

    Interface {
        Sight              = r"interface-gfx\sight.bmp"
        GunsDeagles        = r"interface-gfx\guns\1.bmp"
        GunsMp5            = r"interface-gfx\guns\2.bmp"
        GunsAk74           = r"interface-gfx\guns\3.bmp"
        GunsSteyr          = r"interface-gfx\guns\4.bmp"
        GunsSpas           = r"interface-gfx\guns\5.bmp"
        GunsRuger          = r"interface-gfx\guns\6.bmp"
        GunsM79            = r"interface-gfx\guns\7.bmp"
        GunsBarrett        = r"interface-gfx\guns\8.bmp"
        GunsMinimi         = r"interface-gfx\guns\9.bmp"
        GunsMinigun        = r"interface-gfx\guns\0.bmp"
        GunsSocom          = r"interface-gfx\guns\10.bmp"
        GunsKnife          = r"interface-gfx\guns\knife.bmp"
        GunsChainsaw       = r"interface-gfx\guns\chainsaw.bmp"
        GunsLaw            = r"interface-gfx\guns\law.bmp"
        GunsFlamer         = r"interface-gfx\guns\flamer.bmp"
        GunsBow            = r"interface-gfx\guns\bow.bmp"
        GunsFist           = r"interface-gfx\guns\fist.bmp"
        GunsM2             = r"interface-gfx\guns\m2.bmp"
        Star               = r"interface-gfx\star.bmp"
        Smalldot           = r"interface-gfx\smalldot.bmp"
        Deaddot            = r"interface-gfx\deaddot.bmp"
        Mute               = r"interface-gfx\mute.bmp"
        Prot               = r"interface-gfx\prot.png"
        Scroll             = r"interface-gfx\scroll.png"
        Bot                = r"interface-gfx\bot.bmp"
        Cursor             = r"interface-gfx\cursor.bmp"
        Health             = r"interface-gfx\health.bmp"
        Ammo               = r"interface-gfx\ammo.bmp"
        Jet                = r"interface-gfx\jet.bmp"
        HealthBar          = r"interface-gfx\health-bar.bmp"
        JetBar             = r"interface-gfx\jet-bar.bmp"
        ReloadBar          = r"interface-gfx\reload-bar.bmp"
        Back               = r"interface-gfx\back.bmp"
        Overlay            = r"interface-gfx\overlay.bmp"
        Nade               = r"interface-gfx\nade.bmp"
        Noflag             = r"interface-gfx\noflag.bmp"
        Flag               = r"interface-gfx\flag.bmp"
        ClusterNade        = r"interface-gfx\cluster-nade.bmp"
        Dot                = r"interface-gfx\dot.bmp"
        FireBar            = r"interface-gfx\fire-bar.bmp"
        FireBarR           = r"interface-gfx\fire-bar-r.bmp"
        VestBar            = r"interface-gfx\vest-bar.bmp"
        Menucursor         = r"interface-gfx\menucursor.bmp"
        Arrow              = r"interface-gfx\arrow.bmp"
        TitleL             = r"interface-gfx\title-l.bmp"
        TitleR             = r"interface-gfx\title-r.bmp"
    }
}

gostek_parts! {
    SecondaryDeagles       = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMp5           = Sprite(Weapon::Mp5),             Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryAk74          = Sprite(Weapon::Ak74),            Point( 5, 10), Center( 0.300,  0.250), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySteyr         = Sprite(Weapon::Steyr),           Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySpas          = Sprite(Weapon::Spas),            Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryRuger         = Sprite(Weapon::Ruger),           Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryM79           = Sprite(Weapon::M79),             Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryBarrett       = Sprite(Weapon::Barrett),         Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMinimi        = Sprite(Weapon::Minimi),          Point( 5, 10), Center( 0.300,  0.350), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryMinigun       = Sprite(Weapon::Minigun),         Point( 5, 10), Center( 0.200,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondarySocom         = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryKnife         = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryChainsaw      = Sprite(Weapon::Chainsaw),        Point( 5, 10), Center( 0.250,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryLaw           = Sprite(Weapon::Law),             Point( 5, 10), Center( 0.300,  0.450), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryFlamebow      = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryBow           = Sprite(None),                    Point( 5, 10), Center( 0.300,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    SecondaryFlamer        = Sprite(Weapon::Flamer),          Point( 5, 10), Center( 0.300,  0.300), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    LeftThigh              = Sprite(Gostek::Udo),             Point( 6,  3), Center( 0.200,  0.500), Show(true),  Flip(true),  Team(true),  Flex(5.0), Color(Pants),     Alpha(Base )
    LeftThighDmg           = Sprite(Gostek::RannyUdo),        Point( 6,  3), Center( 0.200,  0.500), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    LeftFoot               = Sprite(Gostek::Stopa),           Point( 2, 18), Center( 0.350,  0.350), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    LeftJetfoot            = Sprite(Gostek::Lecistopa),       Point( 2, 18), Center( 0.350,  0.350), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    LeftLowerleg           = Sprite(Gostek::Noga),            Point( 3,  2), Center( 0.150,  0.550), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Pants),     Alpha(Base )
    LeftLowerlegDmg        = Sprite(Gostek::RannyNoga),       Point( 3,  2), Center( 0.150,  0.550), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    LeftArm                = Sprite(Gostek::Ramie),           Point(11, 14), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    LeftArmDmg             = Sprite(Gostek::RannyRamie),      Point(11, 14), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    LeftForearm            = Sprite(Gostek::Reka),            Point(14, 15), Center( 0.000,  0.500), Show(true),  Flip(false), Team(true),  Flex(5.0), Color(Main),      Alpha(Base )
    LeftForearmDmg         = Sprite(Gostek::RannyReka),       Point(14, 15), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    LeftHand               = Sprite(Gostek::Dlon),            Point(15, 19), Center( 0.000,  0.400), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    GrabbedHelmet          = Sprite(Gostek::Helm),            Point(15, 19), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    GrabbedHat             = Sprite(Gostek::Kap),             Point(15, 19), Center( 0.100,  0.400), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RightThigh             = Sprite(Gostek::Udo),             Point( 5,  4), Center( 0.200,  0.650), Show(true),  Flip(true),  Team(true),  Flex(5.0), Color(Pants),     Alpha(Base )
    RightThighDmg          = Sprite(Gostek::RannyUdo),        Point( 5,  4), Center( 0.200,  0.650), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    RightFoot              = Sprite(Gostek::Stopa),           Point( 1, 17), Center( 0.350,  0.350), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    RightJetfoot           = Sprite(Gostek::Lecistopa),       Point( 1, 17), Center( 0.350,  0.350), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    RightLowerleg          = Sprite(Gostek::Noga),            Point( 4,  1), Center( 0.150,  0.550), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Pants),     Alpha(Base )
    RightLowerlegDmg       = Sprite(Gostek::RannyNoga),       Point( 4,  1), Center( 0.150,  0.550), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Chest                  = Sprite(Gostek::Klata),           Point(10, 11), Center( 0.100,  0.300), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    Vest                   = Sprite(Gostek::Kamizelka),       Point(10, 11), Center( 0.100,  0.300), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    ChestDmg               = Sprite(Gostek::RannyKlata),      Point(10, 11), Center( 0.100,  0.300), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Hip                    = Sprite(Gostek::Biodro),          Point( 5,  6), Center( 0.250,  0.600), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    HipDmg                 = Sprite(Gostek::RannyBiodro),     Point( 5,  6), Center( 0.250,  0.600), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    Head                   = Sprite(Gostek::Morda),           Point( 9, 12), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    HeadDmg                = Sprite(Gostek::RannyMorda),      Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Headblood), Alpha(Blood)
    HeadDead               = Sprite(Gostek::Morda),           Point( 9, 12), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
    HeadDeadDmg            = Sprite(Gostek::RannyMorda),      Point( 9, 12), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Headblood), Alpha(Blood)
    MrT                    = Sprite(Gostek::Hair3),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    Helmet                 = Sprite(Gostek::Helm),            Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    Hat                    = Sprite(Gostek::Kap),             Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RamboBadge             = Sprite(Gostek::Badge),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    HairDreadlocks         = Sprite(Gostek::Hair1),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock1         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.000,  1.220), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock2         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock3         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.040, -0.300), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock4         = Sprite(Gostek::Dred),            Point(23, 24), Center( 0.000, -0.900), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairDreadlock5         = Sprite(Gostek::Dred),            Point(23, 24), Center(-0.200, -1.350), Show(false), Flip(false), Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairPunk               = Sprite(Gostek::Hair2),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    HairNormal             = Sprite(Gostek::Hair4),           Point( 9, 12), Center( 0.000,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Hair),      Alpha(Base )
    Cigar                  = Sprite(Gostek::Cygaro),          Point( 9, 12), Center(-0.125,  0.400), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(Cygar),     Alpha(Base )
    SilverLchain           = Sprite(Gostek::Lancuch),         Point(10, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    SilverRchain           = Sprite(Gostek::Lancuch),         Point(11, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    SilverPendant          = Sprite(Gostek::Metal),           Point(22, 21), Center( 0.500,  0.700), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenLchain           = Sprite(Gostek::Zlotylancuch),    Point(10, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenRchain           = Sprite(Gostek::Zlotylancuch),    Point(11, 22), Center( 0.100,  0.500), Show(false), Flip(false), Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    GoldenPendant          = Sprite(Gostek::Zloto),           Point(22, 21), Center( 0.500,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Base )
    FragGrenade1           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade2           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade3           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade4           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    FragGrenade5           = Sprite(Weapon::FragGrenade),     Point( 5,  6), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade1        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade2        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade3        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade4        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    ClusterGrenade5        = Sprite(Weapon::ClusterGrenade),  Point( 5,  6), Center( 0.500,  0.300), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Nades)
    PrimaryDeagles         = Sprite(Weapon::Deagles),         Point(16, 15), Center( 0.100,  0.800), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryDeaglesClip     = Sprite(Weapon::DeaglesClip),     Point(16, 15), Center( 0.100,  0.800), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryDeaglesFire     = Sprite(Weapon::DeaglesFire),     Point(16, 15), Center(-0.500,  1.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5             = Sprite(Weapon::Mp5),             Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5Clip         = Sprite(Weapon::Mp5Clip),         Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMp5Fire         = Sprite(Weapon::Mp5Fire),         Point(16, 15), Center( -0.65,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74            = Sprite(Weapon::Ak74),            Point(16, 15), Center( 0.150,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74Clip        = Sprite(Weapon::Ak74Clip),        Point(16, 15), Center( 0.150,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryAk74Fire        = Sprite(Weapon::Ak74Fire),        Point(16, 15), Center( -0.37,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyr           = Sprite(Weapon::Steyr),           Point(16, 15), Center( 0.200,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyrClip       = Sprite(Weapon::SteyrClip),       Point(16, 15), Center( 0.200,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySteyrFire       = Sprite(Weapon::SteyrFire),       Point(16, 15), Center( -0.24,  0.750), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpas            = Sprite(Weapon::Spas),            Point(16, 15), Center( 0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpasClip        = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySpasFire        = Sprite(Weapon::SpasFire),        Point(16, 15), Center(-0.200,  0.900), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRuger           = Sprite(Weapon::Ruger),           Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRugerClip       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryRugerFire       = Sprite(Weapon::RugerFire),       Point(16, 15), Center( -0.35,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79             = Sprite(Weapon::M79),             Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79Clip         = Sprite(Weapon::M79Clip),         Point(16, 15), Center( 0.100,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryM79Fire         = Sprite(Weapon::M79Fire),         Point(16, 15), Center(-0.400,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrett         = Sprite(Weapon::Barrett),         Point(16, 15), Center( 0.150,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrettClip     = Sprite(Weapon::BarrettClip),     Point(16, 15), Center( 0.150,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBarrettFire     = Sprite(Weapon::BarrettFire),     Point(16, 15), Center( -0.15,  0.800), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimi          = Sprite(Weapon::Minimi),          Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimiClip      = Sprite(Weapon::MinimiClip),      Point(16, 15), Center( 0.150,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinimiFire      = Sprite(Weapon::MinimiFire),      Point(16, 15), Center(-0.200,  0.900), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigunClip     = Sprite(Weapon::MinigunClip),     Point( 8,  7), Center( 0.500,  0.100), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigun         = Sprite(Weapon::Minigun),         Point(16, 15), Center( 0.050,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryMinigunFire     = Sprite(Weapon::MinigunFire),     Point(16, 15), Center(-0.200,  0.450), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocom           = Sprite(Weapon::Socom),           Point(16, 15), Center( 0.200,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocomClip       = Sprite(Weapon::SocomClip),       Point(16, 15), Center( 0.200,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimarySocomFire       = Sprite(Weapon::SocomFire),       Point(16, 15), Center( -0.24,  0.850), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnife           = Sprite(Weapon::Knife),           Point(16, 20), Center(-0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnifeClip       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryKnifeFire       = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsaw        = Sprite(Weapon::Chainsaw),        Point(16, 15), Center( 0.100,  0.500), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsawClip    = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryChainsawFire    = Sprite(Weapon::ChainsawFire),    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLaw             = Sprite(Weapon::Law),             Point(16, 15), Center( 0.100,  0.600), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLawClip         = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryLawFire         = Sprite(Weapon::LawFire),         Point(16, 15), Center(-0.100,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBow             = Sprite(Weapon::Bow),             Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowArrow        = Sprite(Weapon::BowA),            Point(16, 15), Center( 0.000,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowString       = Sprite(Weapon::BowS),            Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowReload       = Sprite(Weapon::Bow),             Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowArrowReload  = Sprite(Weapon::Arrow),           Point(16, 20), Center( 0.000,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowStringReload = Sprite(Weapon::BowS),            Point(16, 15), Center(-0.400,  0.550), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryBowFire         = Sprite(Weapon::BowFire),         Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamer          = Sprite(Weapon::Flamer),          Point(16, 15), Center( 0.200,  0.700), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamerClip      = Sprite(None),                    Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(true),  Team(false), Flex(0.0), Color(None),      Alpha(Base )
    PrimaryFlamerFire      = Sprite(Weapon::FlamerFire),      Point(16, 15), Center( 0.000,  0.000), Show(false), Flip(false), Team(false), Flex(0.0), Color(None),      Alpha(Base )
    RightArm               = Sprite(Gostek::Ramie),           Point(10, 13), Center( 0.000,  0.600), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Main),      Alpha(Base )
    RightArmDmg            = Sprite(Gostek::RannyRamie),      Point(10, 13), Center(-0.100,  0.500), Show(false), Flip(true),  Team(true),  Flex(0.0), Color(None),      Alpha(Blood)
    RightForearm           = Sprite(Gostek::Reka),            Point(13, 16), Center( 0.000,  0.600), Show(true),  Flip(false), Team(true),  Flex(5.0), Color(Main),      Alpha(Base )
    RightForearmDmg        = Sprite(Gostek::RannyReka),       Point(13, 16), Center( 0.000,  0.600), Show(false), Flip(true),  Team(true),  Flex(5.0), Color(None),      Alpha(Blood)
    RightHand              = Sprite(Gostek::Dlon),            Point(16, 20), Center( 0.000,  0.500), Show(true),  Flip(true),  Team(true),  Flex(0.0), Color(Skin),      Alpha(Base )
}
