use shared::mapfile::MapFile;
use shared::anims::Animation;
use shared::parts::ParticleSystem;
use na::Vector2;

pub struct AnimsList {
    pub run: Animation,
    pub stand: Animation,
    pub run_back: Animation,
    pub jump: Animation,
    pub jump_side: Animation,
    pub roll: Animation,
    pub roll_back: Animation,
    pub fall: Animation,
    pub crouch: Animation,
    pub crouch_run: Animation,
    pub crouch_run_back: Animation,
    pub reload: Animation,
    pub throw: Animation,
    pub recoil: Animation,
    pub shotgun: Animation,
    pub barret: Animation,
    pub small_recoil: Animation,
    pub aim_recoil: Animation,
    pub hands_up_recoil: Animation,
    pub clip_in: Animation,
    pub clip_out: Animation,
    pub slide_back: Animation,
    pub change: Animation,
    pub throw_weapon: Animation,
    pub weapon_none: Animation,
    pub punch: Animation,
    pub reload_bow: Animation,
    pub melee: Animation,
    pub cigar: Animation,
    pub match_: Animation,
    pub smoke: Animation,
    pub wipe: Animation,
    pub groin: Animation,
    pub take_off: Animation,
    pub victory: Animation,
    pub piss: Animation,
    pub mercy: Animation,
    pub mercy2: Animation,
    pub own: Animation,
    pub prone: Animation,
    pub get_up: Animation,
    pub prone_move: Animation,
    pub aim: Animation,
    pub hands_up_aim: Animation
}

pub struct MainState {
    pub map: MapFile,
    pub anims: AnimsList,
    pub sprite_parts: ParticleSystem,
    pub gostek_skeleton: ParticleSystem,
    pub camera: Vector2<f32>,
    pub camera_prev: Vector2<f32>,
    pub mouse: Vector2<f32>,
    pub mouse_prev: Vector2<f32>,
    pub game_width: i32,
    pub game_height: i32,
    pub gravity: f32,
}
