use shared::mapfile::MapFile;
use shared::anims::Animation;
use shared::parts::ParticleSystem;
use na::Vector2;

pub struct AnimsList {
    pub run: Box<Animation>,
    pub stand: Box<Animation>,
    pub run_back: Box<Animation>,
    pub jump: Box<Animation>,
    pub jump_side: Box<Animation>,
    pub roll: Box<Animation>,
    pub roll_back: Box<Animation>,
    pub fall: Box<Animation>,
    pub crouch: Box<Animation>,
    pub crouch_run: Box<Animation>,
    pub crouch_run_back: Box<Animation>,
    pub reload: Box<Animation>,
    pub throw: Box<Animation>,
    pub recoil: Box<Animation>,
    pub shotgun: Box<Animation>,
    pub barret: Box<Animation>,
    pub small_recoil: Box<Animation>,
    pub aim_recoil: Box<Animation>,
    pub hands_up_recoil: Box<Animation>,
    pub clip_in: Box<Animation>,
    pub clip_out: Box<Animation>,
    pub slide_back: Box<Animation>,
    pub change: Box<Animation>,
    pub throw_weapon: Box<Animation>,
    pub weapon_none: Box<Animation>,
    pub punch: Box<Animation>,
    pub reload_bow: Box<Animation>,
    pub melee: Box<Animation>,
    pub cigar: Box<Animation>,
    pub match_: Box<Animation>,
    pub smoke: Box<Animation>,
    pub wipe: Box<Animation>,
    pub groin: Box<Animation>,
    pub take_off: Box<Animation>,
    pub victory: Box<Animation>,
    pub piss: Box<Animation>,
    pub mercy: Box<Animation>,
    pub mercy2: Box<Animation>,
    pub own: Box<Animation>,
    pub prone: Box<Animation>,
    pub get_up: Box<Animation>,
    pub prone_move: Box<Animation>,
    pub aim: Box<Animation>,
    pub hands_up_aim: Box<Animation>
}

pub struct MainState {
    pub map: MapFile,
    pub anims: AnimsList,
    pub soldier_parts: ParticleSystem,
    pub gostek_skeleton: ParticleSystem,
    pub camera: Vector2<f32>,
    pub camera_prev: Vector2<f32>,
    pub mouse: Vector2<f32>,
    pub mouse_prev: Vector2<f32>,
    pub game_width: i32,
    pub game_height: i32,
    pub gravity: f32,
}
