[package]
name = "gfx2d"
version = "0.1.0"
authors = ["Mariano Cuatrin <mariano.cuatrin@gmail.com>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
macroquad = { version = "0.3.0-alpha.0", default-features = false }
image = "0.23"
rgb = "0.8"
gvfs = "0.1"
log = "0.4"
