[package]
name = "soldank-shared"
version = "0.1.0"
authors = ["Tomasz Sterna <tomasz@sterna.link>"]
edition = "2018"
license = "MIT"
publish = false

[dependencies]
cfg-if = "0.1"
log = "0.4"
nanoserde = "0.1"
